### ISSUE TITLE
is it normal?

### ISSUE THREAD

**Issue by marcelo321** [m4ll0k/takeover#11]
Hello, i have been using your tool for some time now and everytime i use it, i always get the same responses, i run:
`python takeover.py --sub-domain-list /root/Desktop/subdomains.txt`
and always get this same response:
Target url... http://www.example.com

over and over again going throw all my subdomain list, but no other error or alert. is it working properly or what?

**Comment by marcelo321** [comment]
i mean, does the tool tell me when its vulnerable?

**Comment by varspare** [comment]
I saw this too, I have a deliberate misconfiguration setup to test against. Ultimately it's because the str conversion wasn't behaving as expected

I've raise PR https://github.com/m4ll0k/takeover/pull/20 to fix this

**Comment by m4ll0k** [comment]
try with new version @marcelo321  @varspare
