### ISSUE TITLE
Import Error in line 14 of takeover.py program

### ISSUE THREAD

**Issue by theredteamhacker** [m4ll0k/takeover#16]
when I run the script using this command: python takeover.py

It showed the following error:

Traceback (most recent call last):
  File "takeover.py", line 14, in <module>
    import urllib.parse
ImportError: No module named parse

**Comment by SimoneBovi** [comment]
You should try to use python3 :)

**Comment by marcelo321** [comment]
i get another error when trying python3, but there should be a fix to the default python2 error

**Comment by m4ll0k** [comment]
try with new version @marcelo321
