### ISSUE TITLE
TabError when running takeover script

### ISSUE THREAD

**Issue by kohldampfer** [m4ll0k/takeover#21]
I just downloaded this repo and tried it on a list of (sub)domains with this command:

` python3 takeover/takeover.py --sub-domain-list path/to/output_file.txt`

And I get this error message:

```
  File "takeover/takeover.py", line 116
    if re.search(code,str(status),re.I) and re.search(error,content.decode(),re.I):
                                                                                  ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by varspare** [comment]
That's my bad, my IDE is setup to use spaces rather than tabs have added PR #23 which includes a fix

**Comment by m4ll0k** [comment]
Try with new version @kohldampfer
