### ISSUE TITLE
Color Code

### ISSUE THREAD

**Issue by jepunband** [m4ll0k/takeover#24]
Hi would it be possible to change the link of the vulnerable sub-domains color.. maybe to Red.
cause as of now when i get this 

[+] Found service: CloudFront
[+] A potential TAKEOVER vulnerability found!

the sub-domain is the same color as the rest which is orange. It will be easier to notice which sub-domains are vulnerable as for now all are the same  color.

thanks.

**Comment by m4ll0k** [comment]
try with new version @jepunband
