### ISSUE TITLE
Tool don't working

### ISSUE THREAD

**Issue by raspberrypl3** [m4ll0k/takeover#26]
Hi m4ll0k!

I installed your tool, which appears to be really good detecting possible subdomain takeovers but I am trying to make it work but the tool never goes further than Domain: https://www.github.com.

I tryied in different distros of linux and different computers but it didn't work in either of them.

Thank you!

![image](https://user-images.githubusercontent.com/36819317/73645940-a535ae80-4678-11ea-960d-03bc78f03622.png)

**Comment by m4ll0k** [comment]
it works but not found a subdomain takeover for https://www.github.com

**Comment by d4rks73ps** [comment]
Does not work for any subdomain ....

**Comment by m4ll0k** [comment]
you need a list domains for github.com, like

```
test.github.com
helloword.github.com
```
at this point: `python3 takeover.py -l github-sub-domains.txt -v `
