### ISSUE TITLE
HTTPSConnectionPool Error

### ISSUE THREAD

**Issue by gorums** [m4ll0k/takeover#32]
/~\
  C oo   ---------------
 _( ^)  |T|A|K|E|O|V|E|R|
/   ~\  ----------------
#> by M'hamed (@m4ll0k) Outaadi
#> http://github.com/m4ll0k
----------------------------------------
[ i ] Starting..
[ i ] Set 1 threads..
[ ! ] HTTPSConnectionPool(host='finance-yql.media.yahoo.com', port=4080): Max retries exceeded with url: /v1/test/console.html (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f831d4c88>: Failed to establish a new connection: [Errno 111] Connection refused'))
[ i ] Domain: query1.finance.yahoo.com

**Comment by m4ll0k** [comment]
your target `finance-yql.media.yahoo.com` isn't a/live 

```js
$ dig finance-yql.media.yahoo.com
```
