### ISSUE TITLE
USAGE

### ISSUE THREAD

**Issue by skynet594** [m4ll0k/takeover#33]
$ python3 takeover.py -d uber-sub-domains.txt -o output.txt -T 3 -v 

kindly change the -d to -l since it's a list of domains.

**Comment by m4ll0k** [comment]
`-d` is for single domain like `www.test.internal.uber.com`

**Comment by skynet594** [comment]
i know the **-d** is for a single domain. But in the usage part you put **-d** instead of **-l** for a list of domain.
i mean python3 takeover.py **-d** uber-sub-domains.txt -o output.txt -T 3 -v 
instead of this python3 takeover.py **-l** uber-sub-domains.txt -o output.txt -T 3 -v

**Comment by m4ll0k** [comment]
next version!
