### ISSUE TITLE
-o does not save the output

### ISSUE THREAD

**Issue by sumgr0** [m4ll0k/takeover#34]
Hi,

When using the tool to runover a list of subdomains, using -o output.txt or output.json does not work and not file is saved.

Also, it just hangs at 99.xx%..

**Comment by m4ll0k** [comment]
it working, try again: `python3 takeover.py -l list-sub-domains.txt -t 5 -o output.json -v`

**Comment by m4ll0k** [comment]
first check if all your targets is alive!!

**Comment by sumgr0** [comment]
Resolving the targets fixed the error of getting stuck at 99.99%.
output.json/txt - works.
Thanks
