### ISSUE TITLE
Not able to identify the vulnerable subdomain in a list.

### ISSUE THREAD

**Issue by sumgr0** [m4ll0k/takeover#35]
Hi,

When using the tool on a list of subdomains, the output data shows the discovery of vulnerable subdomain. It however, only mentions the service not the subdomain itself...

In the snapshot none of the subdomains (before and after the vulnerable service detection) have the mentioned vulnerable error.

![image](https://user-images.githubusercontent.com/11391119/76526079-ffedd180-6492-11ea-9a60-31e1be318c58.png)

**Comment by m4ll0k** [comment]
risolved!

**Comment by sumgr0** [comment]
The latest update fixes the issue.
Thanks for the quick action
