### ISSUE TITLE
Tool doesn't working because of regex pattern

### ISSUE THREAD

**Issue by badvvolf** [m4ll0k/takeover#38]
I found that github.io scanning doesn't work. 
You can get takeoverable response by `<any not exist id>.github.io` and you can use it for test.

It's response includes `<p><strong>There isn\'t a GitHub Pages site here.</strong><p>`, so the fingerprint that this tool use is `There isn\'t a Github Pages site here\.`

But find() returns nothing, and I found that `\'` need to be `\\\'`
Change fingerprint to `There isn\\\'t a Github Pages site here\.` then it works.

I think there are similar problems in other fingerprint too.

**Comment by m4ll0k** [comment]
ok thank's!
